name: Xtensa Rust | x86_64-apple-darwin
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Xtensa Rust release version to build"
        required: true
        default: '1.94.0.2'
      release_tag:
        description: "Release tag where artifacts will be stored (e.g. v1.94.0.2, untagged-00000)"
        required: true
        default: "v1.94.0.2"

jobs:
  build-xtensa-rust:
    name: Build Xtensa Rust
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15-intel]
        include:
          - os: macos-15-intel
            ASSET_PATH: "build/dist/rust-nightly-x86_64-apple-darwin.tar.xz"
            ASSET_NAME: "rust-${{ github.event.inputs.release_version }}-x86_64-apple-darwin.tar.xz"
            ASSET_CONTENT_TYPE: "application/x-tar"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          repository: esp-rs/rust
          ref: esp-${{ github.event.inputs.release_version }}
          submodules: true
      - name: Prepare build
        run: |
          arch -x86_64 python3 src/bootstrap/configure.py --experimental-targets=Xtensa --release-channel=nightly --release-description="${{ github.event.inputs.release_version }}" --enable-extended --enable-cargo-native-static --tools=rustdoc,clippy,cargo,rustfmt,rust-analyzer-proc-macro-srv,src --dist-compression-formats='xz' --set rust.jemalloc --enable-lld --enable-profiler
      - name: Build with x.py - dist packages - with cached LLVM
        run: arch -x86_64 python3 x.py dist --stage 2 || echo "silence pkg build error"
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          repository: JyCyunMe/esp-rs.rust-build
          tag_name: ${{ github.event.inputs.release_tag }}
          files: ${{ matrix.ASSET_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
